<?php

namespace Kurumi\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileGalleryRepository extends EntityRepository
{
}
