<?php

namespace App\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Briareos\ChatBundle\Entity\ChatSubjectRepositoryInterface;
use Briareos\ChatBundle\Entity\ChatSubjectInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements ChatSubjectRepositoryInterface
{
    public function getPresentSubjects(ChatSubjectInterface $subject)
    {
        $presentUsers = $this->findAll();
        $presence = array();
        /** @var $presentUser ChatSubjectInterface */
        foreach ($presentUsers as $presentUser) {
            if ($presentUser->getId() === $subject->getId()) {
                continue;
            }
            $presence[$presentUser->getId()] = array(
                'u' => $presentUser->getId(),
                'n' => $presentUser->getChatName(),
                'p' => 'http://loopj.com/images/facebook_32.png',
                's' => 1,
            );
        }
        return $presence;
    }
}