imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: false }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false
    session:
        storage_id:         session.storage.native
        handler_id:         session.handler.native_file
        name:               kurumi
        #cookie_lifetime
        #cookie_path:       \
        #cookie_domain:     example.com
        #cookie_secure:     true
        cookie_httponly:    true
        save_path:          %kernel.cache_dir%/sessions

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - "BriareosAclBundle::fields.html.twig"
    exception_controller:  Symfony\Bundle\TwigBundle\Controller\ExceptionController::showAction
    globals:
        site_name:  Kurumi
        main_firewall_name: %main_firewall_name%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - PageBundle
        - UserBundle
    read_from: %kernel.root_dir%/../webroot
    node: "C:/Program Files (x86)/nodejs/node.exe"
    java: "C:/Program Files (x86)/Java/jre7/bin/java.exe"
    filters:
        cssrewrite: ~
        yui_css:
            jar: "C:/Users/Fox/Programs/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "C:/Users/Fox/Programs/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar"
        less:
            node: "C:/Program Files (x86)/nodejs/node.exe"
            node_paths:
                - "C:/Program Files (x86)/nodejs/node_module"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: false
        mappings:
            UserBundle: ~
            SonataMediaBundle: ~
            ApplicationSonataMediaBundle: ~
            BriareosNodejsBundle: ~
            BriareosChatBundle: ~
            BriareosAclBundle: ~
        dql:
            string_functions:
                FindInSet: DoctrineExtensions\Query\Mysql\FindInSet
            numeric_functions:
                DEGREES: DoctrineExtensions\Query\Mysql\Degrees
                ACOS: DoctrineExtensions\Query\Mysql\Acos
                SIN: DoctrineExtensions\Query\Mysql\Sin
                RADIANS: DoctrineExtensions\Query\Mysql\Radians
                COS: DoctrineExtensions\Query\Mysql\Cos
        resolve_target_entities:
            Briareos\NodejsBundle\Entity\NodejsSubjectInterface: Kurumi\UserBundle\Entity\User
            Briareos\ChatBundle\Entity\ChatSubjectInterface: Kurumi\UserBundle\Entity\User
            Briareos\AclBundle\Entity\AclSubjectInterface: Kurumi\UserBundle\Entity\User


stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            tree: true
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

lunetics_locale:
    allowed_locales:
        - en_US
        - sr_Cyrl
    guessing_order:
        - router
        - cookie
        - browser
    cookie:
        set_on_detection: true
    switcher:
        template: ::language_switcher.html.twig

fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php
    alias:  %facebook_alias%
    app_id: %facebook_app_id%
    secret: %facebook_secret%
    cookie: %facebook_cookie%
    permissions: %facebook_permissions%

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        sonata.media.block.media:
        sonata.media.block.gallery:
        sonata.media.block.feature_media:

sonata_admin:
    title:      Project Kurumi
    title_logo: /bundles/sonataadmin/logo_title.png
    security:
        handler: sonata.admin.security.handler.briareos_acl
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        dashboard: SonataAdminBundle:Core:dashboard.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

            # Customize this part to add new block configuration
            - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Welcome to the Sonata Admin</h2> <p>This is a <code>sonata.block.service.text</code> from the Block Bundle, you can create and add new block in these area by configuring the <code>sonata_admin</code> section.</p> <br /> For instance, here a RSS feed parser (<code>sonata.block.service.rss</code>):"} }
            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}
        groups:
            users_group:
                label: admin.group.users
                items:
                    - sonata.admin.user
                    - sonata.admin.profile
                    - sonata.admin.briareos_acl.acl_role_admin
            sonata_media:
                label: admin.group.media

sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~

    templates:
        form:
            - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig
        filter:
            - SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig
        types:
            list:
                array:      SonataAdminBundle:CRUD:list_array.html.twig
                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
                date:       SonataAdminBundle:CRUD:list_date.html.twig
                time:       SonataAdminBundle:CRUD:list_time.html.twig
                datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_list_field.html.twig
                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_list_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
                identifier: SonataAdminBundle:CRUD:base_list_field.html.twig

            show:
                array:      SonataAdminBundle:CRUD:show_array.html.twig
                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
                date:       SonataAdminBundle:CRUD:show_date.html.twig
                time:       SonataAdminBundle:CRUD:show_time.html.twig
                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig

sonata_media:
    default_context: default
    db_driver: doctrine_orm
    providers:
        image:
            thumbnail:  sonata.media.thumbnail.liip_imagine
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats: []
        user_picture:
            providers:
                - sonata.media.provider.image
            formats:
                thumbnail:
                    width: 32
                    height: 32
                search:
                    width: 260
                    height: 180
                profile:
                    width: 260
                    height: 420
    cdn:
        server:
            #path: ''
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../webroot/uploads/media
            create:     false

liip_imagine:
    driver:             gd
    web_root:           %kernel.root_dir%/../webroot
    data_root:          %kernel.root_dir%/../webroot
    cache_prefix:       /media/cache
    cache:              web_path
    data_loader:        filesystem
    controller_action:  SonataMediaBundle:Media:liipImagineFilter
    filter_sets:
        admin:
            quality: 100
            format: jpg
            filters:
                thumbnail: { size: [160, 120], mode: inset }
        user_picture_thumbnail:
            quality: 90
            format: jpg
            filters:
                thumbnail: { size: [32, 32], mode: outbound }
        user_picture_search:
            quality: 80
            format: jpg
            filters:
                thumbnail: { size: [260, 180], mode: outbound }
        user_picture_profile:
            quality: 80
            format: jpg
            filters:
                thumbnail: { size: [260, 420], mode: inset }

sonata_intl:
    timezone:
        # default timezone used as fallback
        default: Europe/Belgrade

bazinga_geocoder:
    providers:
        yahoo:
            api_key: %yahoo_api_key%
            locale:  %locale%

old_sound_rabbit_mq:
    connections:
        default:
            host:      'localhost'
            port:      5672
            user:      'guest'
            password:  'guest'
            vhost:     '/'
    producers:
    consumers:

