front:
    pattern: /

kurumi_main:
    resource: "@KurumiMainBundle/Controller/"
    type:     annotation
    prefix:   /

# OAuth start
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

login_check_facebook:
    pattern: /login/check-facebook

login_check_google:
    pattern: /login/check-google

login_check_windows_live:
    pattern: /login/check-windows_live

login_check_yahoo:
    pattern: /login/check-yahoo
# OAuth end

BriareosNodejsBundle:
    resource: "@BriareosNodejsBundle/Controller/"
    type:     annotation
    prefix:   /

BriareosChatBundle:
    resource: "@BriareosChatBundle/Resources/config/routing.xml"
    prefix:   /chat

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_imagine:
    resource: .
    type:     imagine

