hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

login_check_facebook:
    pattern: /login/check-facebook

login_check_google:
    pattern: /login/check-google

login_check_windows_live:
    pattern: /login/check-windows_live

login_check_yahoo:
    pattern: /login/check-yahoo

play:
    resource: "@PlayBundle/Controller/"
    type:     annotation
    prefix:   /connect

front:
    pattern: /

SearchBundle:
    resource: "@SearchBundle/Controller/"
    type:     annotation
    prefix:   /

PageBundle:
    resource: "@PageBundle/Controller/"
    type:     annotation
    prefix:   /

UserBundle:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

BriareosNodejsBundle:
    resource: "@BriareosNodejsBundle/Controller/"
    type:     annotation
    prefix:   /

BriareosChatBundle:
    resource: "@BriareosChatBundle/Controller/"
    type:     annotation
    prefix:   /

LuneticsLocaleBundle:
    resource: "@LuneticsLocaleBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_liip_imagine:
    resource: .
    type: imagine
    prefix: ''

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: "@SonataMediaBundle/Resources/config/routing/gallery.xml"
    prefix: /media/gallery

media:
    resource: "@SonataMediaBundle/Resources/config/routing/media.xml"
    prefix: /media
