NodejsBundle:
    resource: "@NodejsBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    pattern: /

PageBundle:
    resource: "@PageBundle/Controller/"
    type:     annotation
    prefix:   /

UserBundle:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

LuneticsLocaleBundle:
    resource: "@LuneticsLocaleBundle/Resources/config/routing.yml"
    prefix:   /

login_check:
    pattern:  /login_check

logout:
    pattern:  /logout

facebook_check:
    pattern:  /facebook_check

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    #pattern: /dashboard
    type: sonata_admin
    prefix: /admin
