jms_security_extra:
    secure_all_services:    false
    expressions:            false
    enable_iddqd_attribute: false
    cache_dir:              %kernel.cache_dir%/jms_security
    voters:
        disable_authenticated:  false   # Enables 3 basic permission checks, IS_AUTHENTICATED_(ANONYMOUS|REMEMBERED|FULLY)
        disable_role:           true    # Checks against the array of roles given by UserInterface::getRoles()
        disable_acl:            true    # Uses the core ACL component http://symfony.com/doc/current/cookbook/security/acl.html
    method_access_control: []

services:
    authentication_handler:
        class: Kurumi\UserBundle\EventListener\AjaxAuthenticationHandler
        arguments: [ @router ]

security:
    encoders:
        Kurumi\UserBundle\Entity\User: sha512

    providers:
        default_database:
            entity: { class: UserBundle:User, property: email }

    firewalls:
        main:
            pattern: ^/
            form_login:
                username_parameter: email
                password_parameter: password
                csrf_parameter:     _token
                intention:          authenticate
                post_only:          true
                check_path:         /login_check
                login_path:         /login
                csrf_provider:      form.csrf_provider
            logout:
                path:               /logout
                target:             /
                csrf_parameter:     _token
                csrf_provider:      form.csrf_provider
            anonymous: ~
            remember_me:
                key:      %secret%
                lifetime: 86400
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
                remember_me_parameter: remember_me

    access_control:
        - { path: ^/,               roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/login_check,    roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/logout,         roles: [IS_AUTHENTICATED_REMEMBERED] }
        - { path: ^/facebook_check, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/admin/,         roles: [administrator] }
        #- { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
        #- { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
