parameters:
    nodejs.class: App\NodejsBundle\Util\Nodejs
    nodejs.config.host: symfony.servehttp.com
    nodejs.config.port: 8080
    nodejs.config.resource: /socket.io
    nodejs.config.service_key: kurumi2012
    nodejs.config.connect_timeout: 5000
    nodejs_twig_extension.class: App\NodejsBundle\Twig\Extension\Nodejs
    user.listener.class: App\NodejsBundle\Listener\UserListener

services:
    nodejs:
        class: %nodejs.class%
        arguments: [@session, %nodejs.config.host%, %nodejs.config.port%, %nodejs.config.resource%, %nodejs.config.service_key%, %nodejs.config.connect_timeout%]
    nodejs.twig.extension:
        class: %nodejs_twig_extension.class%
        arguments: [@nodejs]
        tags:
            - { name: twig.extension }
    user.listener:
        class: %user.listener.class%
        tags:
            - { name: doctrine.event_listener, event: preRemove }
