Kurumi\MainBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: User with specified email address already exists
            groups: [registration,admin,edit_email]
    properties:
        email:
            - NotBlank:
                message: Please enter an e-mail address
                groups: [registration,admin]
            - NotBlank:
                message: Please enter a new e-mail address.
                groups: [edit_email]
            - Email:
                message: The email entered is invalid
                groups: [registration,admin,edit_email]
        name:
            - NotBlank:
                message: Please enter your first name or nickname
                groups: [registration,admin,edit_name]
            - MinLength:
                limit: 3
                groups: [registration,admin,edit_name]
            - MaxLength:
                limit: 24
                groups: [registration,admin,edit_name]
        currentPassword:
            - Symfony\Component\Security\Core\Validator\Constraint\UserPassword:
                message: The password entered is invalid.
                groups: [edit_email,edit_password]
        plainPassword:
            - NotBlank:
                message: Please enter a password.
                groups: [registration]
            - NotBlank:
                message: Please enter your new password.
                groups: [set_password,edit_password]
        timezone:
            - NotBlank:
                groups: [registration,admin]
        locale:
            - Locale: ~
        profile:
            - Valid: ~
        picture:
            - Valid: ~

Kurumi\MainBundle\Entity\Profile:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [user]
            message: The specified user already has a profile assigned
            groups: [registration,admin]
    properties:
        birthday:
            - NotBlank:
                message: Enter your date of birth
                groups: [registration]
            - Date:
                message: the fuck...
                groups: [registration]
            - Type:
                type: \DateTime
                message: the fuck, man...
                groups: [registration]
            - Kurumi\MainBundle\Validator\MinAge:
                limit: 16
                groups: [registration]
        gender:
            - NotBlank:
                message: Please indicate your gender
                groups: [registration]
        firstName: []
        lastName: []
        user:
            - NotBlank:
                message: Profile owner must be specified.
                groups: [registration,admin]
        lookingFor:
            - NotBlank:
                message: Please specify a gender you're interested in.
                groups: [search]
        lookingAgedFrom:
        lookingAgedTo:
        city:
            - Valid: ~
            - NotBlank:
                groups: [search]
                message: You didn't specify a city we recognize.

Kurumi\MainBundle\Entity\City:
    properties:
        name:
            - NotBlank:
                message: Please enter your city
                groups: [registration]

Application\Sonata\MediaBundle\Entity\Media:
    properties:
        binaryContent:
            - Image:
                mimeTypes:
                    - image/jpeg
                    - image/png
                minWidth: 32
                minHeight: 32
                mimeTypesMessage: You must provide a valid picture in .jpg or .png format.
                groups: [user_picture]
            - NotBlank:
                message: You must select a picture to upload.
                groups: [user_picture,profile_photo]
