<?php

namespace Kurumi\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileCacheRepository extends EntityRepository
{
}
