<?php

namespace Kurumi\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Kurumi\MainBundle\Entity\Profile;
use Kurumi\MainBundle\Entity\City;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{

}