<?php

namespace App\NodejsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChatCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatCacheRepository extends EntityRepository
{
}