<?php

namespace App\NodejsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Briareos\ChatBundle\Entity\ChatSubjectInterface;

/**
 * ChatMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatMessageRepository extends EntityRepository
{

}