parameters:
    # relative to cwd, which is set to /web
    geoip.class: Kurumi\UserBundle\Util\GeoIp
    geoip.location: %kernel.root_dir%/Resources/geoip
    city_to_city_name_transformer.class: Kurumi\UserBundle\Form\DataTransformer\CityToCityNameTransformer
    city_to_city_name_transformer.appid: %yahoo_appid%

services:
    # Form types #
    form.type.detect_timezone:
        class: Kurumi\UserBundle\Form\Type\DetectTimezoneType
        tags:
            - { name: form.type, alias: detect_timezone }
    form.type.gender:
        class: Kurumi\UserBundle\Form\Type\GenderType
        tags:
            - { name: form.type, alias: gender }
    form.type.city:
        class: Kurumi\UserBundle\Form\Type\CityType
        arguments:
            - @city_to_city_name_transformer
        tags:
            - { name: form.type, alias: city }
    form.type.birthday:
        class: Kurumi\UserBundle\Form\Type\BirthdayType
        tags:
            - { name: form.type, alias: birthday }
    city_to_city_name_transformer:
        class: %city_to_city_name_transformer.class%
        arguments:
            - @doctrine.orm.entity_manager
            - Kurumi\UserBundle\Entity\City
            - %city_to_city_name_transformer.appid%
    user_manager:
        class: Kurumi\UserBundle\Entity\UserManager
        arguments: [ @security.encoder_factory ]
    # Register/login users via Facebook OAuth #
    facebook.user:
        class: Kurumi\UserBundle\Security\User\Provider\FacebookProvider
        arguments: [@fos_facebook.api, @doctrine.orm.entity_manager, @validator]

    # Sonata Admin Bundle services #
    sonata.admin.user:
        class: Kurumi\UserBundle\Admin\UserAdmin
        arguments: [ null, Kurumi\UserBundle\Entity\User, SonataAdminBundle:CRUD ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.users }
        calls:
            - [ setUserManager, [ @user_manager ] ]
    sonata.admin.profile:
        class: Kurumi\UserBundle\Admin\ProfileAdmin
        arguments: [ null, Kurumi\UserBundle\Entity\Profile, SonataAdminBundle:CRUD ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.profiles }
    user.permission_container:
        class: Kurumi\UserBundle\Admin\PermissionContainer
        tags:
            - { name: security.permission_container }
    user_manager.listener:
        class: Kurumi\UserBundle\EventListener\UserListener
        arguments: [ @user_manager ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
    user_picture_provider:
        class: Kurumi\UserBundle\User\PictureProvider
        arguments:
            - @doctrine.orm.default_entity_manager
            - Application\Sonata\MediaBundle\Entity\Media
            - none: %genderless_picture_ids%
              male: %male_picture_ids%
              female: %female_picture_ids%
    twig.extension.user_picture_provider:
        class: Kurumi\UserBundle\Twig\Extension\UserPictureProvider
        arguments: [@user_picture_provider]
        tags:
            - { name: twig.extension }
