services:
    validator.timezone:
        class: Kurumi\UserBundle\Validator\TimezoneValidator
        tags:
            - { name: validator.constraint_validator, alias: validator.timezone }
    validator.geoname_id:
        class: Kurumi\UserBundle\Validator\GeonameIdValidator
        arguments: [@geoname_lookup]
        tags:
            - { name: validator.constraint_validator, alias: validator.geoname_id }