<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseGallery as BaseGallery;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Gallery extends BaseGallery
{

    /**
     * @var integer
     */
    protected $id;

    /**
     * @var ArrayCollection
     */
    private $profileGalleries;

    public function __construct()
    {
        parent::__construct();
        $this->profileGalleries = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function getProfileGalleries()
    {
        return $this->profileGalleries;
    }

    public function setProfileGalleries($profileGalleries)
    {
        $this->profileGalleries = $profileGalleries;
    }
}